name: "ecoton-backend-app"

services:
  ecoton-db:
    image: 'postgres:latest'
    tty: true
    env_file: ./.env
    container_name: 'ecoton-db'
    environment:
      - 'POSTGRES_DB=ecoton-db'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
#    volumes:
#      - 'ecoton-db-volume:/var/lib/postgresql/data'

  ecoton-backend:
    image: 'almaxgood/ecoton-backend'
    container_name: 'ecoton-backend'
    env_file: ./.env
    tty: true
    depends_on:
      - ecoton-db
    ports:
      - '8080:8080'
      - '5005:5005'

#volumes:
#  cardio-db-volume: